### ISSUE TITLE
Get an SNMP Agent by ID

### ISSUE THREAD

**Issue by frankhorv** [sonalake/snmp-sim-rust#10]
As a user, I want to get an existing instance of SNMP Agent by using its unique identifier.

**Required API inputs**
- SNMP Agent ID (required)

**API Result**
- The instance of an SNMP Agent (all attributes of SNMP Agent) identified by ID

**Tasks**
- [x]  OpenAPI definition (GET method returning 200)
- [x]  Backend Routes, Domain, Data Access implementation
- [x]  Define CLI
- [x]  Wire CLI to OpenAPI call
- [x]  Integration tests
