### ISSUE TITLE
Get a Managed Device by ID

### ISSUE THREAD

**Issue by frankhorv** [sonalake/snmp-sim-rust#11]
As a user, I want to get an existing instance of Managed Device by using its unique identifier.

**Required API inputs**
- Device ID (required)

**API Result**
- The instance of a Managed Device (all attributes of Managed device including the referenced SNMP Agent attributes) identified by ID

**Tasks**
- [x]  OpenAPI definition (GET method returning 200)
- [x]  Backend Routes, Domain, Data Access implementation
- [x]  Define CLI
- [x]  Wire CLI to OpenAPI call
- [x]  Integration tests
