### ISSUE TITLE
Modify an SNMP Agent

### ISSUE THREAD

**Issue by frankhorv** [sonalake/snmp-sim-rust#12]
As a user, I want to update an existing instance of SNMP Agent by using its unique identifier.

**Required API inputs**
- SNMP Agent ID (required)

**API Result**
- The instance of an SNMP Agent (all attributes of the updated SNMP Agent)

**Tasks**
- [x]  OpenAPI definition (PUT method returning OK 200 or Created 201)
- [x]  Backend Routes, Domain, Data Access implementation
- [x]  Define CLI
- [x]  Wire CLI to OpenAPI call
- [x]  Integration tests
