### ISSUE TITLE
 Delete an SNMP Agent

### ISSUE THREAD

**Issue by frankhorv** [sonalake/snmp-sim-rust#2]
As a user, I want to delete an existing instance of SNMP Agent by using its unique identifier.

**Required API inputs**
- SNMP Agent ID (required)

**API Result**
- The instance of deleted SNMP Agent (all attributes of SNMP Agent)

**Tasks**
- [x]  OpenAPI definition (DELETE method returning Deleted 200 or No Content 204)
- [x]  Backend Routes, Domain, Data Access implementation
- [x]  Define CLI
- [x]  Wire CLI to OpenAPI call
- [x]  Integration tests
