### ISSUE TITLE
List SNMP Agents

### ISSUE THREAD

**Issue by frankhorv** [sonalake/snmp-sim-rust#3]
As a user, I want to get all SNMP Agent instances (+ pagination support).

**Required API inputs**
None

**Optional API inputs**
page as integer => Page index starts from zero, default value is 1.
page_index as integer => Number of results on a page, default value is 20.

**API Result**
All SNMP Agent instances (all attributes of SNMP Agent)

**Tasks**

- [x]  OpenAPI definition (GET method returning 200 + array of Agents)
- [x]  Backend Routes, Domain, Data Access implementation
- [x]  Define CLI
- [x]  Wire CLI to OpenAPI call
- [x]  Integration tests
