### ISSUE TITLE
Create a Managed Device

### ISSUE THREAD

**Issue by frankhorv** [sonalake/snmp-sim-rust#4]
As a user, I want to define a Managed Device running an SNMP Agent.

**Required inputs**
- Managed Device Name
- SNMP Agent ID
- Device IP Address and port (defaults to localhost:161) + IP protocol version (v4 or v6, defaults to v4)
- SNMP protocol version (defaults to SNMPv1)
- SNMP protocol attributes (oneOf, SNMPv3 - security and user attributes, SNMPv1 and SNMPv2 - Community defaults to public)

**Optional inputs**
- Managed Device description

**Result**
- An instance of Managed Device (all input attributes + Managed Device ID)
- Managed Device state (starting, running, stopped)
- or failure - with error description

**Tasks**
- [x] OpenAPI definition (POST method returning Exists 200 or Created 204)
- [x] SQL Table definition
- [x] Backend Routes, Domain, Data Access implementation
- [x] Define CLI
- [x] Wire CLI to OpenAPI calls
- [x] Integration tests
