### ISSUE TITLE
 Modify a Managed Device

### ISSUE THREAD

**Issue by frankhorv** [sonalake/snmp-sim-rust#5]
As a user, I want to update an existing instance of Managed Device by using its unique identifier.

**Required API inputs**
- Device (required)

**API Result**
- The instance of a Managed Device (all attributes of the updated Managed Device with the referenced SNMP Agent attributes)

**Tasks**
- [x]  OpenAPI definition (PUT method returning OK 200 or Created 201)
- [x]  Backend Routes, Domain, Data Access implementation
- [x]  Define CLI
- [x]  Wire CLI to OpenAPI call
- [x]  Integration tests
