### ISSUE TITLE
 Delete a Managed Device

### ISSUE THREAD

**Issue by frankhorv** [sonalake/snmp-sim-rust#6]
As a user, I want to delete an existing instance of Managed Device by using its unique identifier.

**Required API inputs**
- Device ID (required)

**API Result**
- The instance of deleted Managed Device (all attributes of Managed Device with referenced SNMP Agent attributes)

**Tasks**
- [x]  OpenAPI definition (DELETE method returning Deleted 200 or No Content 204)
- [x]  Backend Routes, Domain, Data Access implementation
- [x]  Define CLI
- [x]  Wire CLI to OpenAPI call
- [x]  Integration tests
